In [1]:
import networkx as nx
import numpy as np
from torch_geometric.datasets import Planetoid, CoraFull, PPI, Coauthor, Amazon

In [8]:
#calculate the percentage of elements smaller than the k-th element
def perc(input,k):
    return sum([1 if i else 0 for i in input<input[k]])/float(len(input))

#calculate the percentage of elements larger than the k-th element
def percd(input,k):
    return sum([1 if i else 0 for i in input>input[k]])/float(len(input))

In [14]:
input = np.array([3., 4., 1., 2., 2.1])
cenperc = np.asarray([perc(input, i) for i in range(len(input))])
print(cenperc)
def perc_full_np(input):
    l = len(input)
    indices = np.argsort(input)
    loc = np.zeros(l, dtype=np.float)
    for i in range(l):
        loc[indices[i]] = i
    return loc / l
print(perc_full_np(cenperc))

[0.6 0.8 0.  0.2 0.4]
[0.6 0.8 0.  0.2 0.4]


In [2]:
def centralissimo(G):
    centralities = []
    centralities.append(nx.pagerank(G))                #print 'page rank: check.'
    L = len(centralities[0])
    Nc = len(centralities)
    print('L, Nc', L, Nc)
    cenarray = np.zeros((Nc,L))
    for i in range(Nc):
    	cenarray[i][list(centralities[i].keys())]=list(centralities[i].values())
    normcen = (cenarray.astype(float)-np.min(cenarray,axis=1)[:,None])/(np.max(cenarray,axis=1)-np.min(cenarray,axis=1))[:,None]
    return normcen

In [3]:
# dataset = Planetoid(root='./data/Cora', name='Cora')
dataset = CoraFull(root='./data/CoraFull')

In [4]:
import torch_geometric.utils as tgu
graph = tgu.to_networkx(dataset[0].edge_index)

In [5]:
normcen = centralissimo(graph)

L, Nc 19793 1


In [6]:
normcen.shape

(1, 19793)

In [7]:
normcen

array([[0.04152337, 0.00356879, 0.00356879, ..., 0.00422403, 0.00742059,
        0.00081266]])

In [ ]:
def save_centrality():
    pass